#!/bin/bash

for arg do
  echo "Process \"$arg\" started";
  eval "$arg" & pid=$!
  PID_LIST="$PID_LIST $pid";
done

trap 'kill $PID_LIST' INT

echo "Parallel processes have started";

# shellcheck disable=SC2086
wait $PID_LIST

echo
echo "All processes have completed";