apiVersion: 1

datasources:
  - access: proxy
    jsonData:
      database: maevsi
      postgresVersion: 1500
      sslmode: 'disable'
    name: PostgreSQL
    secureJsonData:
      password: $__file{/run/secrets/postgres_role_grafana_password}
    type: grafana-postgresql-datasource
    url: postgres:5432
    user: $__file{/run/secrets/postgres_role_grafana_username}
