apiVersion: 1

datasources:
  - access: proxy
    jsonData:
      database: maevsi
      postgresVersion: 1500
      sslmode: 'disable'
    name: PostgreSQL
    secureJsonData:
      password: postgres
    type: grafana-postgresql-datasource
    url: postgres:5432
    user: postgres
